<div class="container text-center">

    <hr>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p><strong>&COPY; Copyright 2012 <?= $this->config->getTitulo(); ?> [Mervy Sites]. Todos os direitos reservados.</strong><br/>
                    A reprodução total ou parcial de qualquer meio ou forma sem expressa autorização ou 
                    citação da fonte de <a href="mailto:mervyin[@nospam]yahoo[dot]com[dot]br"><b>Mervy Sites</b></a> é proibida. Legislação: 
                    <a href="http://www.planalto.gov.br/ccivil_03/leis/l9610.htm" target="_blank">clique aqui</a></p>
            </div>                   

        </div>
    </footer>

</div>
<!-- /.container -->

<!-- JavaScript -->
<script src="/web_files/js/jquery-2.1.3.min.js"></script>
<script src="/web_files/js/bootstrap.min.js"></script>
<script src="/web_files/js/tinymce/tinymce.min.js"></script>
<script src="/web_files/js/tinymce/implementar2.js"></script>        
<script src="/web_files/js/tablesorter.min.js"></script>  
<script src="/web_files/js/funcoes.js"></script>
</body>
</html>
