<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><?= $this->config->getTitulo(); ?></title>
        <link href="/web_files/css/bootstrap.min.css" rel="stylesheet">
        <link href="/web_files/css/custom.css" rel="stylesheet">
        <link href="/web_files/imagens/mvcblog.ico" rel="shortcut icon" type="image/x-icon" >         
    </head>
    <body>
        <div class="container">
            <div class="col-lg-12 col-md-12">                
                <div class="page-header">                       
                    <img src="/web_files/imagens/banner.png" alt="" class="img-responsive banner">                   
                    <h1 class="text-center">Área Administrativa</h1>
                </div>                

                <div class="row">                                 
                    <?php if (isset($_SESSION['userData']['nome'])): ?>             
                        <h4 class="text-right">
                            |:::| Usuário: <?= $_SESSION['userData']['nome'] ?>
                            |:::| Nível de acesso: <span style="color:red;"><?= $_SESSION['userData']['nivel'] ?></span>
                        </h4>           
                    </div>
                </div>
            </div>
            <div class="container">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="/"><?= $this->config->getTitulo(); ?></a>        
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li><a href="/admin/cadastrar/<?= $this->getParam(2) ?>">Inserir novos</a></li>  
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Gerenciar <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="/admin/gerenciar/artigos">Artigos</a></li>                          
                                        <li><a href="/admin/gerenciar/albuns">Álbuns</a></li>
                                        <li><a href="/admin/gerenciar/videos">Vídeos</a></li>
                                        <li><a href="/admin/gerenciar/autores">Autores</a></li>
                                        <li><a href="/admin/gerenciar/categorias_artigos">Cat. dos artigos</a></li>
                                        <li><a href="/admin/gerenciar/categorias_videos">Cat. dos vídeos</a></li>
                                    </ul>
                                </li>
                                <li><a href="/admin/upload">Uploads</a></li>
                            </ul>                        
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="/admin/logout">Sair</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            <?php endif; ?>  
        </div>
