<?php require_once("headerAdmin.phtml"); ?>
<p>Inserindo novos <?= ucfirst($view_secao) ?></p>
<form class="opcoes" action='/admin/cadastrar/<?= $this->getParam(2) ?>/do' enctype="multipart/form-data" method="POST">
    <p><label>Login: </label><input type="text" name="login" size="40"/></p>
    <p><label>Nome: </label><input type="text" name="nome" size="70"/></p>
    <p><label>Apelido: </label><input type="text" name="apelido" size="50"/></p>
    <p><label>Email: </label><input type="text" name="email" size="50"/></p>
    <p><label>Senha:</label><input type="text" name="senha" size="50"/></p>
    <p><label>Nível: </label>    
        <input name="nivel" type="radio" value="1" checked>1 (um) - Básico
        <input name="nivel" type="radio" value="2" >2 (dois) - Intermediário
        <input name="nivel" type="radio" value="3" >3 (três) - Avançado                    
    </p>
    <p><label>Status: </label>    
        <input name="status" type="radio" value="ativo" checked>Ativo
        <input name="status" type="radio" value="inativo">Inativo                                       
    </p>                
    <input type="hidden" name="data" value="<?= date("Y-m-d") ?>"/>               
    <p style="text-align: right"><input type="submit" value='Cadastrar' name="inserir" /></p>
</form>    
<?php require_once("footerAdmin.phtml"); ?>