<?php require_once("headerAdmin.phtml"); ?>
<p>Editando dados de <?= ucfirst($view_secao) ?></p>
<form class="opcoes" action='/admin/editar/<?= $this->getParam(2) ?>/<?= $this->getParam(3)?>/do' enctype="multipart/form-data" method="POST">
    <p><label>Login: </label><input type="text" name="login" value="<?= $view_dados['login'] ?>" size="40"/></p>
    <p><label>Nome: </label><input type="text" name="nome" value="<?= $view_dados['nome'] ?>" size="70"/></p>
    <p><label>Apelido: </label><input type="text" name="apelido" value="<?= $view_dados['apelido'] ?>" size="50"/></p>
    <p><label>Email: </label><input type="text" name="email" value="<?= $view_dados['email'] ?>" size="50"/></p>
    <p><label>Senha:</label><input type="password" name="senha" value="" size="50"/></p>
    <p><label>Nível: </label>    
        <input name="nivel" type="radio" value="1" <?= ($view_dados['nivel'] == "1") ? "checked" : "" ?>>1 (um) - Básico
        <input name="nivel" type="radio" value="2" <?= ($view_dados['nivel'] == "2") ? "checked" : "" ?>>2 (dois) - Intermediário
        <input name="nivel" type="radio" value="3" <?= ($view_dados['nivel'] == "3") ? "checked" : "" ?>>3 (três) - Avançado                    
    </p>
    <p><label>Status: </label>    
        <input name="status" type="radio" value="ativo" <?= ($view_dados['status'] == "ativo") ? "checked" : "" ?>>Ativo
        <input name="status" type="radio" value="inativo" <?= ($view_dados['status'] == "inativo") ? "checked" : "" ?>>Inativo                                       
    </p>                
    <input type="hidden" name="data" value="<?= date("Y-m-d") ?>"/>               
    <p style="text-align: right"><input type="submit" value='Alterar' name="alterar" /></p>
</form>      
<?php require_once("footerAdmin.phtml"); ?>

