<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">  
        <meta name="author" content="Merovingio">
        <meta name="robots" content="index, follow">
        <meta http-equiv="Creation-Date" content="2014-04-07">
        <meta name="description" content="<?= $this->config->getDescricao(); ?>">
        <meta name="keywords" content="<?= $this->config->getPalavras_chaves(); ?>">      
        <title><?= $this->config->getTitulo() . ' - ' . ucwords($this->_controller) ?></title>
        <link href="http://mervy.net/libs/css/highslide/highslide.css" rel="stylesheet">
        <link href="/web_files/css/bootstrap.min.css" rel="stylesheet">
        <link href="/web_files/css/custom.css" rel="stylesheet">
        <link href="/web_files/imagens/mvcblog.ico" rel="shortcut icon" type="image/x-icon" >        
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-header">                     
                        <img src="/web_files/imagens/banner.png" alt="" class="img-responsive banner">
                    </div>
                    <div class="bs-component">
                        <div class="navbar navbar-default">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="/"><?= $this->config->getTitulo(); ?></a>
                            </div>
                            <div class="navbar-collapse collapse navbar-responsive-collapse">
                                <ul class="nav navbar-nav">                               
                                    <li<?= ($this->_controller == 'home' && $this->_controller == "") ? " class='active'" : "" ?>><a href="/">Home</a></li>
                                    <li<?= ($this->_controller == 'blog') ? " class='active'" : "" ?>><a href="/blog">Blog</a></li>
                                    <li<?= ($this->_controller == 'noticias') ? " class='active'" : "" ?>><a href="/noticias">Notícias</a></li>
                                    <li<?= ($this->_controller == 'videos') ? " class='active'" : "" ?>><a href="/videos">Vídeos</a></li>
                                    <li<?= ($this->_controller == 'imagens') ? " class='active'" : "" ?>><a href="/imagens">Imagens</a></li>
                                    <li<?= ($this->_controller == 'sobre') ? " class='active'" : "" ?>><a href="/sobre">Sobre</a></li>                                
                                </ul>
                                <form class="navbar-form navbar-right">
                                    <input type="text" class="form-control col-lg-8" placeholder="Search">
                                </form>                          
                            </div>
                        </div>
                        <!--</div>-->
                    </div>
                </div>
            </div>