
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">About
                <small>It's Nice to Meet You!</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a>
                </li>
                <li class="active">About</li>
            </ol>
        </div>
    </div>

    <h3>A nossa missão</h3>
    <p>Apresentar conteúdos de qualidade no formato de textos, vídeos e imagens, que
        sejam atrativos às pessoas tanto do lado prático como do ponto de vista de
        entretenimento e informação.</p>
    <h3>A nossa visão</h3>
    <p> Num mundo em que a tecnologia a cada dia se torna mais presente na vida das
        pessoas e a busca de informações se tornou mais acessível bem como a busca por
        entretenimento, fazemos seleções e criamos conteúdos de
        qualidade e que possam ajudar as pessoas a se instruirem mais bem como se
        divertirem com qualidade e satisfação.</p>
    <h3>Os nossos valores</h3>      
    <ul>
        <li>Conquistar os internautas</li>
        <li>Publicar conteúdos de qualidade</li>
        <li>Selecionar vídeos e imagens otimizadas</li>
        <li>Desenvolver sites úteis e atrativos</li>
        <li>Estimular o retorno de visitantes no site</li>
    </ul>
    <h3>A equipe</h3>
    <h4>Mano Kabuloso</h4>
    <p> Seu apelido foi dado pelos colegas do colégio. Estuda atualmente o 1.º Ano de Ciência da Computação.</p>
    <p>Mano Kabuloso é autodidata e no momento está estudando computação gráfica com os softwares 
        After Effects, Photoshop CS5, Cinema 4D entre outros.</p>
    <p>Faz tutoriais e pesquisa na net e sempre contribui com este site.</p>
    <h4>Merovingio</h4>
    <p><b><a href="http://pt.wikipedia.org/wiki/Diretor_executivo" target="_blank">CEO</a></b> de <b>Mervy Sites</b>.</p>
    <p>O apelido tem a ver com o personagem do filme Matrix. Mervy é um diminutivo dado por outra 
        personagem num dos filmes <b>(Matrix Revolutions 0:23:46)</b>.</p>
    <p>Também é autodidata e no momento está estudando PHP, MySQL, CSS, HTML entre outras 
        linguagens dinâmicas para Web.</p>
    <p>Adora Tecnologia e faz muita leitura sobre temas diversos.</p>
    <p>É formado em Matemática com Pós-graduação em Ensino de Matemática.</p>
    <p>Está estudando e se preparando para uma segunda faculdade nos próximos anos na área de Tecnologia
        ou Engenharia.</p>
    <p>É responsável por todo o código deste site, bem como sua manutenção, além do conteúdo em si.</p>
    <h4>Ivy</h4>
    <p>Participa dando opiniões sobre o que foi postado e o que pode ser melhorado
        no site em termos de layout e conteúdos.</p>
    <p>Contribui também postando alguns conteúdos algumas vezes.</p>     
</div>