<div class="container">
    <h3>Editando artigos</h3>
    <form class="form-horizontal" action='/admin/editar/<?= $this->getParam(2) ?>/<?= $this->getParam(3) ?>/do' enctype="multipart/form-data" method="POST">
        <div class="form-group">
            <label for="titulo" class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
                <input type="titulo" name="titulo" class="form-control" id="titulo" value="<?= $view_dados['titulo'] ?>" >
            </div>
        </div>
        <div class="form-group">
            <label for="imagem" class="col-sm-2 control-label">Imagem</label>
            <div class="col-sm-10">
                <input type="file" name="imagem" class="form-control" id="imagem" value="<?= $view_dados['imagem'] ?>"><?= $view_dados['imagem'] ?>
            </div>
        </div>
        <div class="form-group">
            <label for="categorias_id" class="col-sm-2 control-label">Categoria</label>
            <div class="col-sm-4">
                <select class="form-control" required name='categorias_id'>  
                    <option selected value="<?= $view_dados['categorias_id'] ?>"><span class='current'><?= $view_dados['categoria'] . "\n" ?></span>
                    <?php
                    foreach ($view_categorias_artigos as $cat):
                        if ($view_dados['categoria'] != $cat['categoria']): //Se a categoria já está selecionada, omite ela da lista
                            ?>           
                            <option value="<?= $cat['id'] ?>"><?= $cat['categoria'] . "\n" ?>
                                <?php
                            endif;
                        endforeach;
                        ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="artigo" class="col-sm-2 control-label">Artigo: </label>
            <div class="col-sm-10">
                <textarea id='post' name='artigo'><?= $view_dados['artigo'] ?></textarea><!--Largura e altura definidos em /web_files/js/tinymce/implementar2.js-->    
            </div>
        </div>
        <div class="form-group">
            <label for="autor" class="col-sm-2 control-label">Autor:</label>
            <div class="col-sm-4">
                <select class="form-control" required name='autor'>  
                    <option selected value="<?= $view_dados['autor'] ?>"><?= $view_dados['apelido'] . "\n" ?>
                        <?php
                        foreach ($view_autores as $autor):
                            if ($view_dados['apelido'] != $autor['apelido']): //Se o autor já está selecionado, omite ele da lista
                                ?>
                            <option value="<?= $autor['id'] ?>"><?= $autor['apelido'] ?>
                                <?php
                            endif;
                        endforeach;
                        ?>
                </select> 
            </div>
        </div>  
        <input type="hidden" name="data" value="<?= date('Y-m-d') ?>" />
        <input type="hidden" name="aprovar" value="<?= $view_dados['aprovar'] ?>" />
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="inserir" class="btn btn-default">Editar</button>                
            </div>
        </div>
    </form>
</div>