<div class="container">
    <table class="table table-bordered table-striped text-center">
        <thead>
        <th>Id</th>            
        <th>Aprovado?</th>
        <th>Titulo do artigo</th>
        <th>Categoria</th>
        <th>Imagem</th>
        <th>Autor</th>
        <th>Editar</th>
        <th>Deletar</th>
        <th>Aprovar</th>
        </thead>
        <?php foreach ($view_sql as $sql): ?>
            <tr>
                <td><?= $sql['id'] ?></td>
                <td><?= $sql['aprovar'] ?></td>
                <td class="text-left"><?= $sql['titulo'] ?></td>
                <td><?= $sql['categoria'] ?></td>
                <td class="imgSQL"><img src="/web_files/imagens/artigos/<?= $sql['imagem'] ?>" alt="<?= $sql['imagem'] ?>" /></td>   
                <td><?= $sql['apelido'] ?></td>      
                <td><a href="/admin/editar/<?= $this->getParam(2) ?>/<?= $sql['id'] ?>"><img src="/web_files/imagens/admin/editar.png"></a></td>
                <td><a href="/admin/deletar/<?= $this->getParam(2) ?>/<?= $sql['id'] ?>"  onclick="return confirm('Confirma a exclusão do registro?')">
                        <img src="/web_files/imagens/admin/deletar.png"></a>
                </td>
                <td><a href="/admin/aprovar/<?= $this->getParam(2) ?>/<?= $sql['id'] ?>/<?= $sql['aprovar'] ?>" onclick="return confirm('Confirma a aprovação/desaprovação do artigo?')">
                        <img src="/web_files/imagens/admin/aprovar.png"></a>
                </td>  
            </tr>
        <?php endforeach; ?>            
    </table>
</div>