<div class="container">
    <h3>Inserindo categorias de vídeos</h3>
    <form class="form-horizontal" action='/admin/cadastrar/<?= $this->getParam(2) ?>/do' enctype="multipart/form-data" method="POST">
        <div class="form-group">
            <label for="categoria" class="col-sm-2 control-label">Categoria: </label>
            <div class="col-sm-10">
                <input type="categoria" name="categoria" class="form-control" id="titulo" placeholder="Categoria">
            </div>
        </div>
        <div class="form-group">
            <label for="slug_categoria" class="col-sm-2 control-label">Slug categoria: </label>
            <div class="col-sm-10">
                <input type="slug_categoria" name="slug_categoria" class="form-control" id="titulo" placeholder="Slug categoria">
            </div>
        </div>
        <input type="hidden" name="data" value="<?= date('Y-m-d') ?>" />
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="inserir" class="btn btn-default">Cadastrar</button>                
            </div>
        </div>
</div>

