<div class="container">

    <div class="row">

        <div class="col-lg-12">
            <h1 class="page-header">Galeria de Imagens
                <small><?= $view_result['titulo'] ?></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a>
                </li>
                <li class="active">Galeria de Imagens</li>
            </ol>
        </div>

    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-12">
            <h3><?= $view_result['titulo'] ?>
                <small>em <?= date('d', strtotime($view_result['data'])) ?> <?= date('M', strtotime($view_result['data'])) ?>, <?= date('Y', strtotime($view_result['data'])) ?></small>
            </h3>            
            <p><?= strip_tags($view_result['descricao']) ?></p>            
        </div>
        <?php foreach ($view_imagens as $imagens): ?>
            <div class = "col-md-3 portfolio-item">
                <a href="/web_files/imagens/albuns/<?= $view_result['slug_titulo'] ?>/<?= $imagens ?>" class="highslide" onclick="return hs.expand(this)">
                    <img class = "img-responsive" src="/web_files/imagens/albuns/thumbs.php?img=<?= $view_result['slug_titulo'] ?>/<?= $imagens ?>" alt="<?= $view_result['titulo'] ?>" title="Clique para ampliar" /></a>
            </div>           
        <?php endforeach; ?>
    </div>

    <hr>

    <div class = "row text-center">

        <div class = "col-lg-12">
            <?php if ($this->contar != '1'): ?>            
                <ul class = "pagination">
                    <?php
                    for ($i = 1; $i <= $this->contar; $i++) {
                        if ($i == $this->atual) {
                            printf('<li class="active"><a href="#"> %s </a></li>' . "\n", $i, $i);
                        } else {
                            echo "<li><a href='/imagens/ver/" . $view_result['slug_titulo'] . "/" . $view_result['id'] . "/$i'> $i </a></li>\n";
                        }
                    }
                endif;
                ?>  
            </ul>         
        </div>
    </div>
    <!-- the comment box -->
    <div class="well">
        <h4>Faça um comentário:</h4>
        <?php //require_once '/web_files/marketing/disqus_insighthall.php'; ?>
    </div>
</div>
<!--/.container -->
