<div class="container">

    <div class="row">

        <div class="col-lg-12">
            <h1 class="page-header">Galeria de Imagens                    
            </h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a>
                </li>
                <li class="active">Imagens</li>
            </ol>
        </div>

    </div>
    <!-- /.row -->

    <div class="row">
        <?php
        if ($view_result != NULL):
            foreach ($view_result as $imagens):
                $pics = strip_tags($imagens['imagens']);
                $photos = explode(", ", $pics);
                ?>
                <div class="col-md-4 portfolio-item">
                    <a href="/imagens/ver/<?= $imagens['slug_titulo'] ?>/<?= $imagens['id'] ?>">
                        <img class="img-responsive" src="/web_files/imagens/albuns/thumbs.php?img=<?= $imagens['slug_titulo'] ?>/<?= $photos['0'] ?>">
                    </a>
                    <h3><a href="/imagens/ver/<?= $imagens['slug_titulo'] ?>/<?= $imagens['id'] ?>">
                        <?= (strlen($imagens['titulo']) > 30) ? $this->aux->resumir($imagens['titulo'], 30) : $imagens['titulo']; ?></a>
                    </h3>      
                    <p><?= $this->aux->resumir($imagens['descricao'], 90) ?> </p>
                </div>
                <?php
            endforeach;             
        else:
            ?>
            <p>Nenhum álbum par exibir!</p>
        <?php endif;?>
          </div>
            <?php
        if ($this->contar != '1'):
            ?>
      
        <hr>
        <div class="row text-center">

            <div class="col-lg-12">
                <ul class="pagination">
                    <?php
                    for ($i = 1; $i <= $this->contar; $i++) {
                        if ($i == $this->atual) {
                            printf('<li class="active"><a href="#"> %s </a></li>' . "\n", $i, $i);
                        } else {
                            echo "<li><a href='/imagens/index/$i'> $i </a></li>\n";
                        }
                    }
                endif;
                ?>  

            </ul>
        </div>

    </div>

</div>
<!-- /.container -->
