<div class="container">
    <h3>Editando dados de autores</h3>
    <form class="form-horizontal" action='/admin/editar/<?= $this->getParam(2) ?>/<?= $this->getParam(3)?>/do' enctype="multipart/form-data" method="POST">
        <div class="form-group">
            <label for="login" class="col-sm-2 control-label">Login: </label>
            <div class="col-sm-10">
                <input type="text" name="login" class="form-control" required id="login" value="<?= $view_dados['login'] ?>" >
            </div>
        </div>
        <div class="form-group">
            <label for="nome" class="col-sm-2 control-label">Nome: </label>
            <div class="col-sm-10">
                <input type="text" name="nome" class="form-control" required id="nome" value="<?= $view_dados['nome'] ?>" >
            </div>
        </div> 
        <div class="form-group">
            <label for="apelido" class="col-sm-2 control-label">Apelido: </label>
            <div class="col-sm-10">
                <input type="text" name="apelido" class="form-control" required id="apelido" value="<?= $view_dados['apelido'] ?>" >
            </div>
        </div> 
        <div class="form-group">
            <label for="email" class="col-sm-2 control-label">E-mail: </label>
            <div class="col-sm-10">
                <input type="email" name="email" class="form-control" required id="email" value="<?= $view_dados['email'] ?>" >
            </div>
        </div> 
        <div class="form-group">
            <label class="col-sm-2 control-label">Nível: </label>  
            <div class="col-sm-10">
                <div class="radio">
                    <label><input name="nivel" type="radio" value="1" <?= ($view_dados['nivel'] == "1") ? "checked" : "" ?>>1 (um) - Básico</label>
                    <label><input name="nivel" type="radio" value="2" <?= ($view_dados['nivel'] == "2") ? "checked" : "" ?>>2 (dois) - Intermediário</label>
                    <label><input name="nivel" type="radio" value="3" <?= ($view_dados['nivel'] == "3") ? "checked" : "" ?>>3 (três) - Avançado  </label>
                </div>
            </div>  
        </div>
        <div class="form-group">
            <label for="senha" class="col-sm-2 control-label">Senha: </label>
            <div class="col-sm-10">
                <input type="password" name="senha" class="form-control" required id="senha" placeholder="Senha" >
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Status: </label>  
            <div class="col-sm-10">
                <div class="radio">
                    <label><input name="status" type="radio" value="ativo" <?= ($view_dados['status'] == "ativo") ? "checked" : "" ?>>Ativo</label>
                    <label><input name="status" type="radio" value="inativo" <?= ($view_dados['status'] == "inativo") ? "checked" : "" ?>>Inativo </label>                    
                </div>
            </div>  
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="inserir" class="btn btn-default">Editar</button>                
            </div>
        </div> 
    </form>
</div>

