<div class="container">
    <h3>Editando álbuns</h3>
    <form class="form-horizontal" action='/admin/editar/<?= $this->getParam(2) ?>/<?= $this->getParam(3) ?>/do' enctype="multipart/form-data" method="POST">
        <div class="form-group">
            <label for="titulo" class="col-sm-2 control-label">Título: </label>
            <div class="col-sm-10">
                <input type="titulo" name="titulo" class="form-control" id="titulo" value="<?= $view_dados['titulo'] ?>" >
            </div>
        </div>
        <div class="form-group">
            <label for="slug_titulo" class="col-sm-2 control-label">Slug título: </label>
            <div class="col-sm-10">
                <input type="slug_titulo" name="slug_titulo" class="form-control" id="slug_titulo" value="<?= $view_dados['slug_titulo'] ?>" >
            </div>
        </div>
        <div class="form-group">
            <label for="imagens" class="col-sm-2 control-label">Imagens: </label>
            <div class="col-sm-10">  
                <input type="text" name="imagens" class="form-control" id="imagens" value="<?= $view_dados['imagens'] ?>">
            </div>
        </div>   
        <div class="form-group">
            <label for="descricao" class="col-sm-2 control-label">Descrição: </label>
            <div class="col-sm-10">                
                <textarea id='post' name='descricao'><?= $view_dados['descricao'] ?></textarea><!--Largura e altura definidos em /web_files/js/tinymce/implementar2.js-->    
            </div>
        </div>
        <div class="form-group">
            <label for="autor" class="col-sm-2 control-label">Autor:</label>
            <div class="col-sm-4">
                <select class="form-control" required name='autor'>  
                    <option selected value="<?= $view_dados['autor'] ?>"><?= $view_dados['apelido'] . "\n" ?>
                        <?php
                        foreach ($view_autores as $autor):
                            if ($view_dados['apelido'] != $autor['apelido']): //Se o autor já está selecionado, omite ele da lista
                                ?>
                            <option value="<?= $autor['id'] ?>"><?= $autor['apelido'] ?>
                                <?php
                            endif;
                        endforeach;
                        ?>
                </select> 
            </div>
        </div>  
        <input type="hidden" name="data" value="<?= date('Y-m-d'); ?>" />
        <input type="hidden" name="aprovar" value="<?= $view_dados['aprovar'] ?>" />
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="inserir" class="btn btn-default">Editar</button>                
            </div>
        </div>
    </form>
</div>