<!DOCTYPE html>
<head>
    <title>Arqueria  --)-></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/css.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div align="center">
        <h1>Desative o adblock</h1>
        <p>
            Você está usando Adblock Plus ou qualquer outra coisa que bloqueia as Publicidades.<br>
            Desative o Adblock para prosseguir!<br>
            Só podemos existir graças as publicidades, como todos nossos serviços são gratuitos nós dependemos das publicidades para pagar nossos servidores.<br>
            Por isso pedimos a vocês para permitirem os anúncios na hora de usar o nossos serviços!<br><br>

            <strong>Desabilitando o Adblock:</strong><br>
            <img src="/web_files/imagens/adblock.png" /><br>
            Você só tem que clicar em "Desativar Adblock Plus"<br></p>
    </div>
</body>
</html>