<div class="container">
    <h3>Inserindo vídeos</h3>
    <form class="form-horizontal" action='/admin/cadastrar/<?= $this->getParam(2) ?>/do' enctype="multipart/form-data" method="POST">
        <div class="form-group">
            <label for="titulo" class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
                <input type="text" name="titulo" class="form-control" id="titulo" placeholder="Título do artigo">
            </div>
        </div>       
        <div class="form-group">
            <label for="thumbnail" class="col-sm-2 control-label">Thumbnail: </label>
            <div class="col-sm-10">
                <input type="text" name="thumbnail" class="form-control" id="thumbnail" placeholder="Thumbnail [http://www.youtube.com/watch?v=*dRaz5_0oUU4*]">
            </div>
        </div>
        <div class="form-group">
            <label for="categorias_id" class="col-sm-2 control-label">Categoria</label>
            <div class="col-sm-4">
                <select class="form-control" required name='categorias_id'>  
                    <option size="30" value=''>Categorias</option>
                    <?php foreach ($view_categorias_vid as $cat): ?>
                        <option size="30" value="<?= $cat['id'] ?>"><?= $cat['categoria'] ?>
                        <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="descricao" class="col-sm-2 control-label">Descrição: </label>
            <div class="col-sm-10">
                <textarea name='descricao' row="3"></textarea><!--Largura e altura definidos em /web_files/js/tinymce/implementar2.js-->    
            </div>
        </div>
        <div class="form-group">
            <label for="codigo" class="col-sm-2 control-label">Código: </label>
            <div class="col-sm-10">
                 <input type="text" name="codigo" class="form-control" id="codigo" placeholder="Código de incorporação do youtube/vimeo"> 
            </div>
        </div>
        <div class="form-group">
            <label for="autor" class="col-sm-2 control-label">Autor: </label>
            <div class="col-sm-4">
                <select class="form-control" required name='autor'>  
                    <option value=''>Autor</option>
                    <?php foreach ($view_autores as $autor): ?>
                        <option size="30" value="<?= $autor['id'] ?>"><?= $autor['apelido'] ?>
                        <?php endforeach; ?>
                </select> 
            </div>
        </div>  
        <input type="hidden" name="data" value="<?= date('Y-m-d') ?>" />
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="inserir" class="btn btn-default">Cadastrar</button>                
            </div>
        </div>
    </form>
</div>

