Plantas,Dicotiledónea,1
Plantas,Allioideae,3
Plantas,Allioideae,3
Plantas,Tépala,4
Plantas,Tépala,4
Plantas,Tépala,4
Plantas,Tépala,4
Animais,Chaetognatha,5
Animais,Chaetognatha,5
Animais,Chaetognatha,5
Animais,Chaetognatha,5
Animais;Chaetognatha;5
Animais;Chaetognatha;5
Animais;Chaetognatha;5
Animais;Chaetognatha;5
Plantas;Dicotiledónea;1
Animais;Chaetognatha;5
Animais;Chaetognatha;5
Animais;Deuterostomia;6
Animais;Lofóforo;7
Animais;Deuterostomia;6
Animais;Deuterostomia;6
Animais;Deuterostomia;6
Animais;Deuterostomia;6
Animais;Deuterostomia;6
Animais;Lofóforo;7
Animais;Lofóforo;7
Animais;Lofóforo;7
Animais;Lofóforo;7
Plantas;Tépala;4
Plantas;Tépala;4
Plantas;Tépala;4
Plantas;Tépala;4
Plantas;Tépala;4
Plantas;Tépala;4
Plantas;Dicotiledónea;1
Plantas;Dicotiledónea;1
Plantas;Dicotiledónea;1
Plantas;Dicotiledónea;1
Plantas;Dicotiledónea;1
Plantas;Dicotiledónea;1
Plantas;Tépala;4
